apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
data:
  config.toml: |
    concurrent = 2
    check_interval = 0
    [[runners]]
      name = "gitlab-runner"
      url = "https://gitlab.com/"
      token = $token
      executor = "kubernetes"
      output_limit = 51200
      [runners.kubernetes]      
        host = "https://xxx.xxx.xxx.xxx:6443"
        cert_file = "/etc/gitlab-runner/tls.crt"
        key_file = "/etc/gitlab-runner/tls.key"
        ca_file = "/etc/gitlab-runner/ca.crt"
        namespace = "default"
        pull_policy = "if-not-present"
        cpu_limit = "0.5"
        cpu_request = "0.5"
        memory_limit = "1Gi"
        memory_request = "1Gi"
        helper_cpu_limit = "0.5"
        helper_cpu_request = "0.5"
        helper_memory_limit = "1Gi"
        helper_memory_request  = "1Gi"
        helper_image = "gitlab/gitlab-runner-helper:x86_64-latest"
        [runners.kubernetes.pod_annotations]
          "k8s.aliyun.com/eci-image-cache" = "true" 
        [runners.kubernetes.volumes]
          [[runners.kubernetes.volumes.pvc]]
            name = "gitlab-runner-cache-pvc"
            mount_path = "/cache"
            readonly = false
          [[runners.kubernetes.volumes.pvc]]
            name = "gitlab-runner-maven-pvc"
            mount_path = "/root/.m2"
            readonly = false
          [[runners.kubernetes.volumes.secret]]
            name = "registry-auth-secret"
            mount_path = "/root/.docker"
            read_only = false
          [runners.kubernetes.volumes.secret.items]
            ".dockerconfigjson" = "config.json"
