apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-runner-maven-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  mountOptions:
  - nolock,noresvport,noacl,hard
  - vers=3
  - rsize=1048576
  - wsize=1048576
  - proto=tcp
  - timeo=600
  - retrans=2
  nfs:
    path: /share
    server: 0079f226-s3vx.cn-hangzhou.extreme.nas.aliyuncs.com
