apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  annotations:
    "k8s.aliyun.com/eci-with-eip": "true" #自动挂载EIP
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123456"
    livenessProbe:
      tcpSocket:
        port: 3306
    ports:
    - containerPort: 3306
      name: mysql
  - image: wordpress:4.8-apache
    name: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    - name: WORDPRESS_DB_PASSWORD
      value: "123456"
    ports:
    - containerPort: 80
      name: wordpress
    volumeMounts:
    - name: wordpress-persistent-storage
      mountPath: /var/www/html
  volumes: #使用云盘作为文件存储，生命周期随pod实例周期释放
  - name: wordpress-persistent-storage
    flexVolume:
      driver: "alicloud/disk"
      fsType: "ext4"
      options:
        volumeType: "alicloud-disk-essd"
        volumeSize: "20Gi"